"""ORM models for MIYA (spec §4).

Conventions:
  * Money is ``NUMERIC(14, 2)`` paired with a ``currency`` enum column.
  * Every timestamp is ``timestamptz``; the application timezone is Asia/Tashkent.
  * Anything derived from an interaction carries ``source_interaction_id`` so a
    purge of that interaction cascades to the rows it produced.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from miya.config import settings
from miya.db import enums as e
from miya.db.base import Base, created_at_column, money_column, pg_enum

# --- Native enum types (single instance each; see pg_enum docstring) ---------
CURRENCY = pg_enum(e.Currency, e.CURRENCY_ENUM)
INTERACTION_SOURCE = pg_enum(e.InteractionSource, e.INTERACTION_SOURCE_ENUM)
DIRECTION = pg_enum(e.Direction, e.DIRECTION_ENUM)
CHAT_TYPE = pg_enum(e.ChatType, e.CHAT_TYPE_ENUM)
DEBT_DIRECTION = pg_enum(e.DebtDirection, e.DEBT_DIRECTION_ENUM)
DEBT_STATUS = pg_enum(e.DebtStatus, e.DEBT_STATUS_ENUM)
PROMISE_MADE_BY = pg_enum(e.PromiseMadeBy, e.PROMISE_MADE_BY_ENUM)
PROMISE_STATUS = pg_enum(e.PromiseStatus, e.PROMISE_STATUS_ENUM)
TRANSACTION_TYPE = pg_enum(e.TransactionType, e.TRANSACTION_TYPE_ENUM)
EVENT_SOURCE = pg_enum(e.EventSource, e.EVENT_SOURCE_ENUM)
EVENT_STATUS = pg_enum(e.EventStatus, e.EVENT_STATUS_ENUM)
TASK_PRIORITY = pg_enum(e.TaskPriority, e.TASK_PRIORITY_ENUM)
TASK_STATUS = pg_enum(e.TaskStatus, e.TASK_STATUS_ENUM)
WINDOW_STATUS = pg_enum(e.WindowStatus, e.WINDOW_STATUS_ENUM)


class Person(Base):
    __tablename__ = "people"

    id: Mapped[int] = mapped_column(primary_key=True)
    display_name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # Alternate spellings the owner actually uses: "Akmal aka", "Akmal GZ".
    aliases: Mapped[list[str]] = mapped_column(
        ARRAY(sa.Text), nullable=False, server_default="{}"
    )
    telegram_id: Mapped[int | None] = mapped_column(sa.BigInteger, unique=True)
    telegram_username: Mapped[str | None] = mapped_column(sa.Text)
    phone: Mapped[str | None] = mapped_column(sa.Text)
    # Who this is to the owner ("yetkazib beruvchi", "mijoz"), set by hand
    # through people.set_relationship (build step 4).
    relationship_: Mapped[str | None] = mapped_column("relationship", sa.Text)
    # The short written profile — MIYA's own prose about the person,
    # regenerated by the worker when there is newer activity than
    # ``profile_updated_at``. Never a source of figures: those are SQL.
    notes: Mapped[str | None] = mapped_column(sa.Text)
    profile_updated_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True)
    )
    created_at: Mapped[datetime] = created_at_column()
    updated_at: Mapped[datetime] = created_at_column(onupdate=sa.func.now())

    __table_args__ = (
        sa.Index("ix_people_display_name", "display_name"),
        sa.Index("ix_people_phone", "phone"),
        sa.Index("ix_people_aliases", "aliases", postgresql_using="gin"),
    )


class ChatMonitor(Base):
    """Which Telegram chats the userbot is allowed to ingest (spec §6)."""

    __tablename__ = "chat_monitors"

    id: Mapped[int] = mapped_column(primary_key=True)
    tg_chat_id: Mapped[int] = mapped_column(sa.BigInteger, unique=True, nullable=False)
    chat_type: Mapped[e.ChatType] = mapped_column(CHAT_TYPE, nullable=False)
    title: Mapped[str | None] = mapped_column(sa.Text)
    # Default: private chats on, groups and channels off until whitelisted.
    # Vision is on everywhere: receipts and invoices arrive as images.
    monitor_enabled: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    vision_enabled: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.true()
    )
    docs_enabled: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.true()
    )
    # New groups, one tap (build step 2): when the owner was asked "o'qiymi?"
    # about a group or channel that started switched off — asked once, ever.
    asked_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # A "Ha" also requests a backfill of the last chats.BACKFILL_DAYS. The bot
    # records the request; the userbot, the only process with a Telegram user
    # session, performs it on its next sweep and stamps ``backfill_done_at``.
    backfill_requested_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True)
    )
    backfill_done_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    backfill_attempts: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="0"
    )
    # The question budget (WP-16, 0014): who decided whether the group is
    # read — 'owner' | 'rule:channel' | 'rule:ignored' | 'rule:legacy' —
    # and the activity that ranks an undecided group in the digest.
    decided_by: Mapped[str | None] = mapped_column(sa.String(16))
    offered_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    digest_shows: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default="0"
    )
    seen_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, server_default="0"
    )
    last_seen_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    owner_active_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    addressed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # Catch-up after downtime (WP-21, 0015): when the chat was switched on
    # (never read before it) and the newest message id the userbot saw.
    monitoring_since: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    last_seen_message_id: Mapped[int | None] = mapped_column(sa.BigInteger)
    updated_at: Mapped[datetime] = created_at_column(onupdate=sa.func.now())


class ConversationWindow(Base):
    """A flushed slice of one chat's conversation, extracted as a unit (spec §7B).

    The userbot stores each message as its own interaction; a window groups the
    consecutive ones and is what actually goes to the extractor, so a debt
    mentioned across three messages is understood as one fact. Extraction runs
    through the Batch API (half price), hence the explicit lifecycle.
    """

    __tablename__ = "conversation_windows"

    id: Mapped[int] = mapped_column(primary_key=True)
    tg_chat_id: Mapped[int] = mapped_column(sa.BigInteger, nullable=False)
    person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="SET NULL")
    )
    started_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    ended_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    message_count: Mapped[int] = mapped_column(sa.Integer, nullable=False)
    char_count: Mapped[int] = mapped_column(sa.Integer, nullable=False)
    # The rendered [ME] / [THEM (Name)] transcript handed to the extractor.
    text: Mapped[str] = mapped_column(sa.Text, nullable=False)
    status: Mapped[e.WindowStatus] = mapped_column(
        WINDOW_STATUS, nullable=False, server_default=e.WindowStatus.pending.value
    )
    # Anthropic Message Batches identifiers: the job, and this window's slot.
    batch_id: Mapped[str | None] = mapped_column(sa.Text)
    custom_id: Mapped[str] = mapped_column(sa.Text, unique=True, nullable=False)
    attempts: Mapped[int] = mapped_column(sa.Integer, nullable=False, server_default="0")
    submitted_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    applied_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # The instant path (build step 2): a private chat, or a group window with
    # a message aimed at the owner, is extracted in real time by the window
    # job rather than waiting for the next batch. Cleared if that keeps
    # failing, so the window falls back onto the batch ladder.
    instant: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.Index("ix_conversation_windows_status", "status", "created_at"),
        sa.Index("ix_conversation_windows_batch", "batch_id"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_conversation_windows_person", "person_id"),
    )


class Interaction(Base):
    """Every input lands here first, before extraction."""

    __tablename__ = "interactions"

    id: Mapped[int] = mapped_column(primary_key=True)
    source: Mapped[e.InteractionSource] = mapped_column(
        INTERACTION_SOURCE, nullable=False
    )
    direction: Mapped[e.Direction] = mapped_column(
        DIRECTION, nullable=False, server_default=e.Direction.na.value
    )
    person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="SET NULL")
    )
    tg_chat_id: Mapped[int | None] = mapped_column(sa.BigInteger)
    occurred_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    raw_text: Mapped[str | None] = mapped_column(sa.Text)
    transcript: Mapped[str | None] = mapped_column(sa.Text)
    # {type, path, mime, size, caption, processed, sha256, ...}
    media: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    summary: Mapped[str | None] = mapped_column(sa.Text)
    meta: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSONB)
    # When the codes in this row's text were indexed into code_mentions
    # (WP-30, 0017); NULL = not yet.
    codes_indexed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    processed: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    # Set when extraction failed validation twice — data is never dropped.
    needs_review: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    created_at: Mapped[datetime] = created_at_column()

    # Set once a userbot message has been claimed by a conversation window;
    # the window owns extraction for every message it contains (spec §7B).
    window_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("conversation_windows.id", ondelete="SET NULL")
    )

    person: Mapped[Person | None] = relationship(lazy="raise")

    __table_args__ = (
        sa.Index("ix_interactions_occurred_at", "occurred_at"),
        sa.Index("ix_interactions_chat_occurred", "tg_chat_id", "occurred_at"),
        sa.Index("ix_interactions_person", "person_id"),
        # The per-person timeline: newest first, paged by occurred_at.
        sa.Index(
            "ix_interactions_person_occurred",
            "person_id",
            sa.text("occurred_at DESC"),
        ),
        sa.Index(
            "ix_interactions_unprocessed",
            "created_at",
            postgresql_where=sa.text("processed = false"),
        ),
        # The window flush job asks "which userbot messages are unclaimed?"
        # every few minutes; keep that off a sequential scan.
        sa.Index(
            "ix_interactions_unwindowed",
            "tg_chat_id",
            "occurred_at",
            postgresql_where=sa.text("window_id IS NULL AND source = 'telegram_userbot'"),
        ),
        # Call-recording dedupe: hash lookups happen once a minute (spec §7C).
        sa.Index(
            "ix_interactions_media_sha256",
            sa.text("(media ->> 'sha256')"),
            postgresql_where=sa.text("source = 'phone_call'"),
        ),
        # Phone-event dedupe (build step 6): one row per call-log entry or
        # SMS, ever. The key is minted on the phone, so a retried batch lands
        # here instead of becoming a second interaction — the unique index,
        # not the ingester's pre-select, is the idempotency guarantee.
        sa.Index(
            "ux_interactions_event_key",
            sa.text("(media ->> 'event_key')"),
            unique=True,
            postgresql_where=sa.text("media ->> 'event_key' IS NOT NULL"),
        ),
        # Reinstall-safe dedupe (WP-11): the event key carries the device id,
        # which a reinstall re-mints; the content key is the message itself.
        sa.Index(
            "ux_interactions_content_key",
            sa.text("(media ->> 'content_key')"),
            unique=True,
            postgresql_where=sa.text("media ->> 'content_key' IS NOT NULL"),
        ),
        # One row per Telegram message (WP-21): the catch-up sweep and the
        # live handler may ingest the same message at once.
        sa.Index(
            "ux_interactions_tg_message",
            "tg_chat_id",
            sa.text("((metadata ->> 'tg_message_id')::bigint)"),
            unique=True,
            postgresql_where=sa.text(
                "source = 'telegram_userbot' AND metadata ? 'tg_message_id'"
            ),
        ),
        sa.Index(
            "ix_interactions_codes_unindexed",
            "id",
            postgresql_where=sa.text("codes_indexed_at IS NULL"),
        ),
        sa.Index(
            "ix_interactions_money_notice_pending",
            "occurred_at",
            postgresql_where=sa.text(
                "(metadata ? 'money_notice') AND NOT (metadata ? 'money_notified')"
            ),
        ),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_interactions_window", "window_id"),
    )


class Debt(Base):
    __tablename__ = "debts"

    id: Mapped[int] = mapped_column(primary_key=True)
    direction: Mapped[e.DebtDirection] = mapped_column(DEBT_DIRECTION, nullable=False)
    person_id: Mapped[int] = mapped_column(
        sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False
    )
    amount: Mapped[Decimal] = money_column(nullable=False)
    currency: Mapped[e.Currency] = mapped_column(
        CURRENCY, nullable=False, server_default=e.Currency.UZS.value
    )
    reason: Mapped[str | None] = mapped_column(sa.Text)
    status: Mapped[e.DebtStatus] = mapped_column(
        DEBT_STATUS, nullable=False, server_default=e.DebtStatus.open.value
    )
    due_date: Mapped[date | None] = mapped_column(sa.Date)
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    notes: Mapped[str | None] = mapped_column(sa.Text)
    created_at: Mapped[datetime] = created_at_column()
    settled_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # Every owner correction, oldest first: [{at, field, old, new, by}, ...].
    # Lives on the row so a purge of the row takes its audit trail with it.
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )

    person: Mapped[Person] = relationship(lazy="raise")
    payments: Mapped[list[DebtPayment]] = relationship(
        back_populates="debt", lazy="raise", cascade="all, delete-orphan"
    )

    __table_args__ = (
        sa.CheckConstraint("amount > 0", name="ck_debts_amount_positive"),
        sa.Index("ix_debts_status_person", "status", "person_id"),
        sa.Index("ix_debts_due_date", "due_date"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_debts_person", "person_id"),
        sa.Index("ix_debts_source_interaction", "source_interaction_id"),
    )


class DebtPayment(Base):
    __tablename__ = "debt_payments"

    id: Mapped[int] = mapped_column(primary_key=True)
    debt_id: Mapped[int] = mapped_column(
        sa.ForeignKey("debts.id", ondelete="CASCADE"), nullable=False
    )
    amount: Mapped[Decimal] = money_column(nullable=False)
    currency: Mapped[e.Currency] = mapped_column(CURRENCY, nullable=False)
    paid_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    note: Mapped[str | None] = mapped_column(sa.Text)

    debt: Mapped[Debt] = relationship(back_populates="payments", lazy="raise")

    __table_args__ = (
        sa.CheckConstraint("amount > 0", name="ck_debt_payments_amount_positive"),
        sa.Index("ix_debt_payments_debt", "debt_id"),
        sa.Index("ix_debt_payments_paid_at", "paid_at"),
    )


class Promise(Base):
    __tablename__ = "promises"

    id: Mapped[int] = mapped_column(primary_key=True)
    made_by: Mapped[e.PromiseMadeBy] = mapped_column(PROMISE_MADE_BY, nullable=False)
    person_id: Mapped[int] = mapped_column(
        sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False
    )
    description: Mapped[str] = mapped_column(sa.Text, nullable=False)
    due_date: Mapped[date | None] = mapped_column(sa.Date)
    status: Mapped[e.PromiseStatus] = mapped_column(
        PROMISE_STATUS, nullable=False, server_default=e.PromiseStatus.open.value
    )
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = created_at_column()
    completed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )

    person: Mapped[Person] = relationship(lazy="raise")

    __table_args__ = (
        sa.Index("ix_promises_status_due", "status", "due_date"),
        sa.Index("ix_promises_person", "person_id"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_promises_source_interaction", "source_interaction_id"),
    )


class Transaction(Base):
    __tablename__ = "transactions"

    id: Mapped[int] = mapped_column(primary_key=True)
    type: Mapped[e.TransactionType] = mapped_column(TRANSACTION_TYPE, nullable=False)
    amount: Mapped[Decimal] = money_column(nullable=False)
    currency: Mapped[e.Currency] = mapped_column(
        CURRENCY, nullable=False, server_default=e.Currency.UZS.value
    )
    category: Mapped[str | None] = mapped_column(sa.Text)
    description: Mapped[str | None] = mapped_column(sa.Text)
    counterparty_person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="SET NULL")
    )
    occurred_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = created_at_column()
    # The ledger (WP-11, 0013). A row is never deleted to correct it: it is
    # voided with a reason, and every change is appended to ``history``.
    # Money totals filter on queries.ACTIVE_TXN.
    voided_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    void_reason: Mapped[str | None] = mapped_column(sa.Text)
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )
    card_last4: Mapped[str | None] = mapped_column(sa.String(4))
    # 'sms:<normalised sender>' | 'app:<package>' | NULL for typed/extracted
    channel: Mapped[str | None] = mapped_column(sa.Text)
    # A transfer between the owner's own accounts: not income, not expense.
    is_internal: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )

    counterparty: Mapped[Person | None] = relationship(lazy="raise")
    # Every text (SMS, app notification) that reported this one payment.
    evidence: Mapped[list[TransactionEvidence]] = relationship(
        lazy="raise", cascade="all, delete-orphan"
    )

    __table_args__ = (
        sa.CheckConstraint("amount > 0", name="ck_transactions_amount_positive"),
        sa.CheckConstraint(
            "card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$'",
            name="ck_transactions_card_last4",
        ),
        sa.Index("ix_transactions_occurred_type", "occurred_at", "type"),
        sa.Index("ix_transactions_category", "category"),
        # The cross-channel match: the same payment seen twice.
        sa.Index(
            "ix_transactions_money_match", "currency", "type", "amount", "occurred_at"
        ),
        sa.Index("ix_transactions_counterparty", "counterparty_person_id"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_transactions_source_interaction", "source_interaction_id"),
    )


class TransactionEvidence(Base):
    """One text that reported a transaction. A payment seen through two
    channels (the bank SMS and the Payme push) is one transaction with two
    evidence rows; each interaction backs at most one transaction."""

    __tablename__ = "transaction_evidence"

    id: Mapped[int] = mapped_column(primary_key=True)
    transaction_id: Mapped[int] = mapped_column(
        sa.ForeignKey("transactions.id", ondelete="CASCADE"), nullable=False
    )
    interaction_id: Mapped[int] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE"), nullable=False
    )
    channel: Mapped[str] = mapped_column(sa.Text, nullable=False)
    card_last4: Mapped[str | None] = mapped_column(sa.String(4))
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.UniqueConstraint("interaction_id", name="ux_transaction_evidence_interaction"),
        sa.UniqueConstraint(
            "transaction_id", "channel", name="ux_transaction_evidence_txn_channel"
        ),
    )


class Event(Base):
    __tablename__ = "events"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(sa.Text, nullable=False)
    start_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
    end_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    location: Mapped[str | None] = mapped_column(sa.Text)
    attendees: Mapped[list[Any] | None] = mapped_column(JSONB)
    description: Mapped[str | None] = mapped_column(sa.Text)
    source: Mapped[e.EventSource] = mapped_column(
        EVENT_SOURCE, nullable=False, server_default=e.EventSource.manual.value
    )
    gcal_event_id: Mapped[str | None] = mapped_column(sa.Text, unique=True)
    status: Mapped[e.EventStatus] = mapped_column(
        EVENT_STATUS, nullable=False, server_default=e.EventStatus.planned.value
    )
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.Index("ix_events_start_at", "start_at"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_events_source_interaction", "source_interaction_id"),
    )


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(primary_key=True)
    description: Mapped[str] = mapped_column(sa.Text, nullable=False)
    due_date: Mapped[date | None] = mapped_column(sa.Date)
    priority: Mapped[e.TaskPriority] = mapped_column(
        TASK_PRIORITY, nullable=False, server_default=e.TaskPriority.med.value
    )
    status: Mapped[e.TaskStatus] = mapped_column(
        TASK_STATUS, nullable=False, server_default=e.TaskStatus.todo.value
    )
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    related_promise_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("promises.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = created_at_column()
    completed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )

    __table_args__ = (
        sa.Index("ix_tasks_status_due", "status", "due_date"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_tasks_source_interaction", "source_interaction_id"),
        sa.Index("ix_tasks_related_promise", "related_promise_id"),
    )


class Claim(Base):
    """Something a counterparty asserted, held until the owner answers (step 3).

    "You owe me 5 mln", "I paid you back", "you promised to send the documents"
    — said by the other side, not the owner. The owner's decision is that such
    a claim is asked about and never written silently, so the extracted item
    waits here as ``payload`` (the pydantic item, as JSON) until a button or a
    command accepts it (the row is then written through the usual writer and
    named by ``result_kind``/``result_id``) or declines it (nothing written).
    Edits before the answer land in ``payload`` and are audited in ``history``.
    """

    __tablename__ = "claims"

    id: Mapped[int] = mapped_column(primary_key=True)
    # The interaction the words came from: the window's synthetic interaction
    # on the userbot path, the bot or call interaction otherwise. A purge of
    # that interaction takes the unanswered question with it.
    interaction_id: Mapped[int] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE"), nullable=False
    )
    # Resolved on accept, or earlier when the window already knows the person.
    person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="SET NULL")
    )
    # The name as extracted; '' when the item named nobody.
    person_name: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="", server_default=""
    )
    # debt | settlement | transaction | promise | fulfilment
    kind: Mapped[str] = mapped_column(sa.String(16), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    # pending | accepted | declined | auto
    state: Mapped[str] = mapped_column(
        sa.String(16), nullable=False, server_default="pending"
    )
    asked_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    answered_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # button | command | auto:bank | auto:own | auto:duplicate
    answered_by: Mapped[str | None] = mapped_column(sa.String(16))
    # What accepting wrote: debt | payment | transaction | promise | fulfilment
    # (the promise a fulfilment closed). Null when accepting only produced a
    # question, e.g. a settlement that matched no open debt.
    result_kind: Mapped[str | None] = mapped_column(sa.String(16))
    result_id: Mapped[int | None] = mapped_column(sa.Integer)
    # Edits before the answer: [{at, field, old, new, by}, ...].
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )
    created_at: Mapped[datetime] = created_at_column()
    # The question budget (WP-16, 0014): the claim this one repeats, and the
    # bank transaction that settles it without asking.
    duplicate_of: Mapped[int | None] = mapped_column(
        sa.ForeignKey("claims.id", ondelete="SET NULL")
    )
    evidence_txn_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("transactions.id", ondelete="SET NULL")
    )

    __table_args__ = (
        sa.Index("ix_claims_interaction", "interaction_id"),
        sa.Index("ix_claims_state_created", "state", "created_at"),
        sa.Index(
            "ix_claims_duplicate_of",
            "duplicate_of",
            postgresql_where=sa.text("duplicate_of IS NOT NULL"),
        ),
        sa.Index(
            "ux_claims_evidence_txn",
            "evidence_txn_id",
            unique=True,
            postgresql_where=sa.text("evidence_txn_id IS NOT NULL"),
        ),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_claims_person", "person_id"),
    )


class ClientCode(Base):
    """A client code (GS367) held by a person (WP-30, 0017).

    At most one active holder per code, enforced by the database; a person
    may hold several. Moves detach the old row and keep its history;
    suggestions wait here until the owner answers.
    """

    __tablename__ = "client_codes"

    id: Mapped[int] = mapped_column(primary_key=True)
    code: Mapped[str] = mapped_column(sa.Text, nullable=False)
    person_id: Mapped[int] = mapped_column(
        sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False
    )
    # active | suggested | rejected | detached
    status: Mapped[str] = mapped_column(
        sa.String(16), nullable=False, server_default="active"
    )
    # command | import | contact | tg_name | extraction
    source: Mapped[str] = mapped_column(sa.String(16), nullable=False)
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    note: Mapped[str | None] = mapped_column(sa.Text)
    asked_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    answered_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    history: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )
    created_at: Mapped[datetime] = created_at_column()
    updated_at: Mapped[datetime] = created_at_column(onupdate=sa.func.now())

    person: Mapped[Person] = relationship(lazy="raise")

    __table_args__ = (
        sa.CheckConstraint(
            "code ~ '^[A-Z]{1,4}[0-9]{1,9}$'", name="ck_client_codes_format"
        ),
        sa.CheckConstraint(
            "status IN ('active','suggested','rejected','detached')",
            name="ck_client_codes_status",
        ),
        sa.Index(
            "ux_client_codes_active_code",
            "code",
            unique=True,
            postgresql_where=sa.text("status = 'active'"),
        ),
        sa.Index("ux_client_codes_code_person", "code", "person_id", unique=True),
        sa.Index("ix_client_codes_person", "person_id"),
        sa.Index(
            "ix_client_codes_suggested",
            "created_at",
            postgresql_where=sa.text("status = 'suggested'"),
        ),
        sa.Index("ix_client_codes_source_interaction", "source_interaction_id"),
    )


class CodeMention(Base):
    """A client code or waybill that one interaction's text named (WP-30)."""

    __tablename__ = "code_mentions"

    id: Mapped[int] = mapped_column(sa.BigInteger, primary_key=True)
    interaction_id: Mapped[int] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE"), nullable=False
    )
    # client | waybill
    kind: Mapped[str] = mapped_column(sa.String(8), nullable=False)
    code: Mapped[str] = mapped_column(sa.Text, nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        sa.CheckConstraint("kind IN ('client','waybill')", name="ck_code_mentions_kind"),
        sa.UniqueConstraint(
            "interaction_id", "kind", "code", name="ux_code_mentions_interaction_code"
        ),
        sa.Index("ix_code_mentions_code_occurred", "code", sa.text("occurred_at DESC")),
    )


class QuestionLog(Base):
    """One tap-request slot spent (WP-16): what was put in front of the owner,
    how, and when. Answers to the owner's own commands are never logged."""

    __tablename__ = "question_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    # claim | missed | still_open | nudge | groups | media | money
    kind: Mapped[str] = mapped_column(sa.String(16), nullable=False)
    # 'c12' | 'm881' | 'debt:3:they_owe_me:UZS' | 'promise:7' | 'task:3' |
    # 'q990' | 'g41' | 'i55' | 's990'
    ref: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # push | brief | evening | receipt
    via: Mapped[str] = mapped_column(sa.String(8), nullable=False)
    tg_message_id: Mapped[int | None] = mapped_column(sa.BigInteger)
    # Always written by the app (record_shown(now=...)); the default is a
    # fallback only.
    sent_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )

    __table_args__ = (
        sa.CheckConstraint(
            "kind IN ('claim','missed','still_open','nudge','groups','media','money')",
            name="ck_question_log_kind",
        ),
        sa.CheckConstraint(
            "via IN ('push','brief','evening','receipt')", name="ck_question_log_via"
        ),
        sa.Index("ix_question_log_sent_at", "sent_at"),
        sa.Index("ix_question_log_kind_ref", "kind", "ref", "sent_at"),
    )


class Memory(Base):
    """RAG store: durable facts + interaction summaries, embedded with bge-m3."""

    __tablename__ = "memories"

    id: Mapped[int] = mapped_column(primary_key=True)
    content: Mapped[str] = mapped_column(sa.Text, nullable=False)
    embedding: Mapped[list[float] | None] = mapped_column(Vector(settings.embed_dim))
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="CASCADE")
    )
    # The person this fact is about, when known (build step 4): the person
    # on the source interaction, or the one person the extraction wrote
    # about. Facts that name nobody in particular stay NULL and are still
    # found by similarity.
    person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="SET NULL")
    )
    occurred_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(sa.Text), nullable=False, server_default="{}"
    )
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.Index("ix_memories_occurred_at", "occurred_at"),
        sa.Index("ix_memories_person_occurred", "person_id", sa.text("occurred_at DESC")),
        sa.Index("ix_memories_tags", "tags", postgresql_using="gin"),
        sa.Index(
            "ix_memories_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_memories_source_interaction", "source_interaction_id"),
        sa.Index(
            "ix_memories_unembedded", "id", postgresql_where=sa.text("embedding IS NULL")
        ),
    )


class DailyReport(Base):
    __tablename__ = "daily_reports"

    id: Mapped[int] = mapped_column(primary_key=True)
    report_date: Mapped[date] = mapped_column(sa.Date, nullable=False)
    content: Mapped[str] = mapped_column(sa.Text, nullable=False)
    stats: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = created_at_column()
    # The delivery ledger (WP-49, 0019): one row per day and kind; the
    # message parts, how many went out, and when all of them had.
    kind: Mapped[str] = mapped_column(
        sa.String(16), nullable=False, server_default="evening"
    )
    window_start: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    window_end: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    parts: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")
    )
    parts_sent: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default="0"
    )
    prose_status: Mapped[str] = mapped_column(
        sa.String(16), nullable=False, server_default="none"
    )
    delivered_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )

    __table_args__ = (
        sa.UniqueConstraint("report_date", "kind", name="uq_daily_reports_date_kind"),
        sa.CheckConstraint("kind IN ('evening','morning')", name="ck_daily_reports_kind"),
        sa.CheckConstraint(
            "prose_status IN ('model','cached','fallback','none')",
            name="ck_daily_reports_prose_status",
        ),
    )


class UsageLog(Base):
    """Per-call cost accounting for Anthropic and ElevenLabs (spec §9)."""

    __tablename__ = "usage_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    provider: Mapped[str] = mapped_column(sa.Text, nullable=False)  # anthropic|elevenlabs
    model: Mapped[str | None] = mapped_column(sa.Text)
    operation: Mapped[str | None] = mapped_column(sa.Text)  # extract|report|rag|...
    input_tokens: Mapped[int | None] = mapped_column(sa.Integer)
    output_tokens: Mapped[int | None] = mapped_column(sa.Integer)
    cache_read_tokens: Mapped[int | None] = mapped_column(sa.Integer)
    cache_write_tokens: Mapped[int | None] = mapped_column(sa.Integer)
    audio_seconds: Mapped[Decimal | None] = mapped_column(sa.Numeric(10, 2))
    batch: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    cost_usd: Mapped[Decimal | None] = mapped_column(sa.Numeric(12, 6))
    source_interaction_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("interactions.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.Index("ix_usage_log_created_at", "created_at"),
        # Foreign keys that cascade or set null are indexed (WP-23, 0016).
        sa.Index("ix_usage_log_source_interaction", "source_interaction_id"),
    )


class ReminderLog(Base):
    """One row per reminder actually sent, so nothing is pinged twice in a day."""

    __tablename__ = "reminder_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    kind: Mapped[str] = mapped_column(sa.Text, nullable=False)  # debt|promise|task|event
    # Stable key for the thing reminded about: a row id, or "person:currency"
    # for a debt balance that spans several rows.
    ref: Mapped[str] = mapped_column(sa.Text, nullable=False)
    sent_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.Index("ix_reminder_log_kind_ref_sent", "kind", "ref", "sent_at"),
    )


class Heartbeat(Base):
    """Liveness ledger (build step 5): one row per process or scheduler job.

    ``component`` is "bot" / "worker" / "userbot" / "api" / "backup" or
    "job:<scheduler job id>". Each writer upserts its own row through
    ``services.health.beat``; ``detail`` is replaced whole on every beat
    (``{"enabled": false}`` marks a userbot switched off on purpose, which
    is not a fault). Nothing here is owner data — the table is wiped and
    rebuilt by the processes themselves.
    """

    __tablename__ = "heartbeats"

    component: Mapped[str] = mapped_column(sa.Text, primary_key=True)
    last_seen_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    detail: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")
    )


__all__ = [
    "ChatMonitor",
    "Claim",
    "ClientCode",
    "CodeMention",
    "DailyReport",
    "Debt",
    "DebtPayment",
    "Event",
    "Heartbeat",
    "Interaction",
    "Memory",
    "Person",
    "Promise",
    "QuestionLog",
    "ReminderLog",
    "Task",
    "Transaction",
    "TransactionEvidence",
    "UsageLog",
]


# --- the one re-index listener (WP-39) -------------------------------------------


@sa.event.listens_for(sa.orm.Session, "before_flush")
def _reindex_changed_text(session, flush_context, instances) -> None:
    """An interaction whose words changed (text, transcript, image
    description) is indexed again: its code mentions — and, once it exists,
    its search row — are reset for the worker to rebuild. Bulk updates
    bypass this; none of them touches text."""
    for obj in session.dirty:
        if not isinstance(obj, Interaction):
            continue
        state = sa.inspect(obj)
        changed = any(
            state.attrs[name].history.has_changes() for name in ("raw_text", "transcript")
        )
        if not changed:
            history = state.attrs.meta.history
            if history.has_changes():
                old = (history.deleted[0] if history.deleted else None) or {}
                new = obj.meta or {}
                changed = old.get("vision") != new.get("vision")
        if not changed:
            continue
        if obj.codes_indexed_at is not None:
            obj.codes_indexed_at = None
        if getattr(obj, "search_indexed_at", None) is not None:
            obj.search_indexed_at = None


class RecapDigest(Base):
    """One or two model-written sentences about a person or a group in a
    recap window (WP-52, 0020), cached by the input they were written from.
    Never a source of figures: the prose is refused if it holds a digit."""

    __tablename__ = "recap_digests"

    id: Mapped[int] = mapped_column(primary_key=True)
    digest_date: Mapped[date] = mapped_column(sa.Date, nullable=False)
    subject_key: Mapped[str] = mapped_column(sa.String(64), nullable=False)
    person_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("people.id", ondelete="CASCADE")
    )
    tg_chat_id: Mapped[int | None] = mapped_column(sa.BigInteger)
    window_start: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    window_end: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    input_hash: Mapped[str] = mapped_column(sa.CHAR(64), nullable=False)
    source_interaction_ids: Mapped[list[int]] = mapped_column(
        ARRAY(sa.Integer), nullable=False, server_default="{}"
    )
    prose: Mapped[str] = mapped_column(sa.Text, nullable=False)
    model: Mapped[str] = mapped_column(sa.String(64), nullable=False)
    created_at: Mapped[datetime] = created_at_column()

    __table_args__ = (
        sa.UniqueConstraint(
            "digest_date",
            "subject_key",
            "input_hash",
            name="uq_recap_digests_subject_input",
        ),
        sa.Index("ix_recap_digests_date_end", "digest_date", "window_end"),
        sa.Index("ix_recap_digests_person", "person_id"),
    )
